language: node_js
node_js:
  - stable
script:
  - npm run build
before_deploy:
  - echo "davidorlea.de" > build/dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/dist
  on:
    branch: master
