name: Lint

on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
